Atualizar o conexao

diff --git a/h/sshplus/Modulos/conexao b/h/sshplus/Modulos/conexao
--- a/h/sshplus/Modulos/conexao
+++ b/h/sshplus/Modulos/conexao
@@ -63,6 +63,14 @@ fun_conexao() {
 			echo -e "\033[1;31m○ "
 			fi`;
 			clear
+			var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
+			clear 
+			echo -e ""
+			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
+				sts3="\033[1;32m◉ "
+			} || {
+				sts3="\033[1;31m○ "
+			}
         echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\E[41;1;37m    ⇱         SSHPLUS  by: @alfalemos        ⇲    \E[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
@@ -70,14 +78,14 @@ fun_conexao() {
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET \033[1;31m                [\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mPROXY DRAGON \033[1;31m
 [\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mPROXY RUST \033[1;31m               [\033[1;36m12\033[1;31m] \033[1;37m• \033[1;33mPROXY DT V1 \033[1;31m
-[\033[1;36m03\033[1;31m] \033[1;37m\033[1;37m• \033[1;33mSSL TUNNEL \033[1;31m               [\033[1;36m13\033[1;31m] \033[1;37m• \033[1;33mPROXY DT V2 \033[1;31m
-[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO 2 ALFA \033[1;31m        [\033[1;36m14\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO KIRITO \033[1;31m
+[\033[1;36m03\033[1;31m] \033[1;37m\033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m             [\033[1;36m13\033[1;31m] \033[1;37m• \033[1;33mPROXY DT V2 \033[1;31m
+[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO 2 ALFA $var_sks1\033[1;31m      [\033[1;36m14\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO KIRITO $var_sks1\033[1;31m
 [\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS \033[1;31m                  [\033[1;36m15\033[1;31m] \033[1;37m• \033[1;33mV2RAY $xv2ray\033[1;31m
 [\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mRESOLVEDOR LOCAL\033[1;31m          [\033[1;36m16\033[1;31m] \033[1;37m• \033[1;33m(HTOP) \033[1;31m
-[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER DTUNNEL \033[1;31m        [\033[1;36m17\033[1;31m] \033[1;37m• \033[1;33mMEMÓRIA VIRTUAL\033[1;31m
-[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER 4G \033[1;31m             [\033[1;36m18\033[1;31m] \033[1;37m• \033[1;33mINFO VPS \033[1;31m
-[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mRELATORIO DE USUARIOS \033[1;31m    [\033[1;36m19\033[1;31m] \033[1;37m• \033[1;33mMENU \033[1;31m>\033[1;33m>\033[1;32m>\033[0m\033[1;31m
-[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mMENU ONLINE \033[1;31m          [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m<\033[0m \033[0m
+[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER DTUNNEL \033[1;31m        [\033[1;36m17\033[1;31m] \033[1;37m• \033[1;33mMENU \033[1;31m>\033[1;33m>\033[1;32m>\033[0m\033[1;31m
+[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER 4G \033[1;31m             [\033[1;36m18\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mMEMÓRIA VIRTUAL \033[1;31m    
+[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mMENU ONLINE \033[1;31m              
 \033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
 			echo ""
 			tput civis
@@ -86,75 +94,73 @@ fun_conexao() {
 			tput cnorm
 			clear
 			case $x in
-			1 | 01)
-				wsmenu
+			1 | 01) 
+			wsmenu
 				;;
 			2 | 02)
-				proxyrust
+			proxyrust
 				;;
 			3 | 03)
-				stunnel2
+			stunnel2
 				;;
 			4 | 04)
-				badvpn.sh
+			badvpn.sh
 				;;
 			5 | 05)
-				slow_setup
+			slow_setup
 				;;
 			6 | 06)
-				dnsserv
+			dnsserv
 				;;
 			7 | 07)
-				menu_check
+			menu_check
 				;;
 			8 | 08)
-				initcheck
+			wget -O /etc/rec/licence "https://raw.githubusercontent.com/sofrenoob/Gggggg/refs/heads/main/h/sshplus/Modulos/licence" -o /dev/null
+			clear
+			initcheck
 				;;
 			9 | 09)
-				slow_setup
+			swapmemory.sh
 				;;
 			    10)
-				bash <(wget -qO- raw.githubusercontent.com/sofrenoob/Gggggg/main/mau/online)
+			    bash <(wget -qO- raw.githubusercontent.com/sofrenoob/Gggggg/main/mau/online)
 				;;
 			    11)
-				proxyd
+			    proxyd
 				;;
 			    12)
 			    proxydtv1
 			    ;;
 		        13)
-				proxydtv2
+		        proxydtv2
 				;;
 			    14)
-				badvpn
+			    wget -O /etc/rec/licence "https://raw.githubusercontent.com/sofrenoob/Gggggg/refs/heads/main/h/sshplus/Modulos/licence" -o /dev/null
+			    clear
+			    badvpn
 				;;
 			    15)
-				v2rayinst
+			    v2rayinst
 				;;
 			    16)
-				htop.sh
+			    htop.sh
 				;;
 			    17)
-				swapmemory.sh
+			    clear
+			    menu
 				;;
 			    18)
-				fun_chisel
-				;;
-			    19)
+			    echo -e "\033[1;31mSaindo...\033[0m"
+			    sleep 1
 			    clear
-				menu
-				;;
-			    20)
-				echo -e "\033[1;31mSaindo...\033[0m"
-				sleep 1
-				clear
-				exit
+			    exit
 				;;
 	     		*)
-				echo -e "\033[1;31mOpcao invalida !\033[0m"
-				sleep 1
+	     		echo -e "\033[1;31mOpcao invalida !\033[0m"
+	     		sleep 1
 				;;
 			esac
 		done
-	}
-	fun_conexao
+}
+fun_conexao
